
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: frankenstein_development
  username: postgres
  host: localhost

test:
  <<: *default
  database: frankenstein_test
  username: postgres
  host: localhost

#production:
#  <<: *default
#  database: frankenstein_production
#  username: frankenstein
#  password: <%= ENV['FRANKENSTEIN_DATABASE_PASSWORD'] %>
